// MOW Plugin gRPC 接口定义
//
// 本文件定义 Core 与 Plugin 之间通信的所有消息与服务。
// - 语言无关：可用于生成 Go / Rust / Python / Node 客户端与服务端
// - 版本演进：新增字段只能追加，禁止修改已有字段编号
// - 状态：Draft v0.1，与 docs/plugin-system.md 与 docs/command-engine.md 对齐

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command 的权限等级，与 docs/permission.md 对齐。
type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED Permission = 0
	Permission_PERMISSION_READ        Permission = 1 // 只读
	Permission_PERMISSION_WRITE       Permission = 2 // 写文件 / 修改配置
	Permission_PERMISSION_EXECUTE     Permission = 3 // 执行命令
	Permission_PERMISSION_DANGEROUS   Permission = 4 // 不可逆或高影响，必须二次确认
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "PERMISSION_UNSPECIFIED",
		1: "PERMISSION_READ",
		2: "PERMISSION_WRITE",
		3: "PERMISSION_EXECUTE",
		4: "PERMISSION_DANGEROUS",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED": 0,
		"PERMISSION_READ":        1,
		"PERMISSION_WRITE":       2,
		"PERMISSION_EXECUTE":     3,
		"PERMISSION_DANGEROUS":   4,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_CANCEL      SignalType = 1 // 取消，等价于 context cancel
	SignalType_SIGNAL_TYPE_INT         SignalType = 2 // SIGINT
	SignalType_SIGNAL_TYPE_TERM        SignalType = 3 // SIGTERM
	SignalType_SIGNAL_TYPE_KILL        SignalType = 4 // SIGKILL
	SignalType_SIGNAL_TYPE_WINCH       SignalType = 5 // 终端尺寸变化（stdout_data 可承载新尺寸）
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_CANCEL",
		2: "SIGNAL_TYPE_INT",
		3: "SIGNAL_TYPE_TERM",
		4: "SIGNAL_TYPE_KILL",
		5: "SIGNAL_TYPE_WINCH",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_TYPE_CANCEL":      1,
		"SIGNAL_TYPE_INT":         2,
		"SIGNAL_TYPE_TERM":        3,
		"SIGNAL_TYPE_KILL":        4,
		"SIGNAL_TYPE_WINCH":       5,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

type ChunkStream int32

const (
	ChunkStream_CHUNK_STREAM_UNSPECIFIED ChunkStream = 0
	ChunkStream_CHUNK_STREAM_STDOUT      ChunkStream = 1
	ChunkStream_CHUNK_STREAM_STDERR      ChunkStream = 2
	ChunkStream_CHUNK_STREAM_STRUCTURED  ChunkStream = 3 // 结构化事件流（例如进度、事件）
)

// Enum value maps for ChunkStream.
var (
	ChunkStream_name = map[int32]string{
		0: "CHUNK_STREAM_UNSPECIFIED",
		1: "CHUNK_STREAM_STDOUT",
		2: "CHUNK_STREAM_STDERR",
		3: "CHUNK_STREAM_STRUCTURED",
	}
	ChunkStream_value = map[string]int32{
		"CHUNK_STREAM_UNSPECIFIED": 0,
		"CHUNK_STREAM_STDOUT":      1,
		"CHUNK_STREAM_STDERR":      2,
		"CHUNK_STREAM_STRUCTURED":  3,
	}
)

func (x ChunkStream) Enum() *ChunkStream {
	p := new(ChunkStream)
	*p = x
	return p
}

func (x ChunkStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkStream) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[3].Descriptor()
}

func (ChunkStream) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[3]
}

func (x ChunkStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkStream.Descriptor instead.
func (ChunkStream) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

type CallerType int32

const (
	CallerType_CALLER_TYPE_UNSPECIFIED CallerType = 0
	CallerType_CALLER_TYPE_CLI         CallerType = 1
	CallerType_CALLER_TYPE_DESKTOP     CallerType = 2
	CallerType_CALLER_TYPE_API         CallerType = 3
	CallerType_CALLER_TYPE_AI          CallerType = 4
	CallerType_CALLER_TYPE_WORKFLOW    CallerType = 5
	CallerType_CALLER_TYPE_RECIPE      CallerType = 6
)

// Enum value maps for CallerType.
var (
	CallerType_name = map[int32]string{
		0: "CALLER_TYPE_UNSPECIFIED",
		1: "CALLER_TYPE_CLI",
		2: "CALLER_TYPE_DESKTOP",
		3: "CALLER_TYPE_API",
		4: "CALLER_TYPE_AI",
		5: "CALLER_TYPE_WORKFLOW",
		6: "CALLER_TYPE_RECIPE",
	}
	CallerType_value = map[string]int32{
		"CALLER_TYPE_UNSPECIFIED": 0,
		"CALLER_TYPE_CLI":         1,
		"CALLER_TYPE_DESKTOP":     2,
		"CALLER_TYPE_API":         3,
		"CALLER_TYPE_AI":          4,
		"CALLER_TYPE_WORKFLOW":    5,
		"CALLER_TYPE_RECIPE":      6,
	}
)

func (x CallerType) Enum() *CallerType {
	p := new(CallerType)
	*p = x
	return p
}

func (x CallerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallerType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[4].Descriptor()
}

func (CallerType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[4]
}

func (x CallerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallerType.Descriptor instead.
func (CallerType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type MetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 插件基础信息
	Metadata *PluginMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// 插件提供的所有 Command 定义
	Commands []*CommandDefinition `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	// 插件提供的所有 Recipe 定义（可选）
	Recipes []*RecipeDefinition `protobuf:"bytes,3,rep,name=recipes,proto3" json:"recipes,omitempty"`
	// 插件提供的所有 Workflow 定义（可选）
	Workflows []*WorkflowDefinition `protobuf:"bytes,4,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// 声明的连接类型（例：ssh / docker / http）
	ConnectionTypes []string `protobuf:"bytes,5,rep,name=connection_types,json=connectionTypes,proto3" json:"connection_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetMetadata() *PluginMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MetadataResponse) GetCommands() []*CommandDefinition {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MetadataResponse) GetRecipes() []*RecipeDefinition {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *MetadataResponse) GetWorkflows() []*WorkflowDefinition {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *MetadataResponse) GetConnectionTypes() []string {
	if x != nil {
		return x.ConnectionTypes
	}
	return nil
}

type PluginMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 唯一标识，例："ssh"、"docker"、"pve"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 展示名，例："SSH"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 语义化版本，例："0.1.0"
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author      string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Homepage    string `protobuf:"bytes,6,opt,name=homepage,proto3" json:"homepage,omitempty"`
	License     string `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	// 依赖的 Core 版本（语义化范围，例：">=0.1.0,<0.2.0"）
	CoreVersion string `protobuf:"bytes,8,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	// 依赖的其他 Plugin ID
	PluginDependencies []string `protobuf:"bytes,9,rep,name=plugin_dependencies,json=pluginDependencies,proto3" json:"plugin_dependencies,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetadata) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *PluginMetadata) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginMetadata) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *PluginMetadata) GetPluginDependencies() []string {
	if x != nil {
		return x.PluginDependencies
	}
	return nil
}

type CommandDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin 内部的 Command ID（例："exec"、"upload"）
	// 对外全限定 ID 由 Core 拼接为 "{plugin_id}.{command_id}"
	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Permission  Permission `protobuf:"varint,3,opt,name=permission,proto3,enum=mow.plugin.v1.Permission" json:"permission,omitempty"`
	// 是否为流式 Command（决定客户端应走 Execute 还是 ExecuteStream）
	Streaming bool `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// 输入 / 输出 JSON Schema（字符串形式）
	InputSchema  string `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema string `protobuf:"bytes,6,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// 是否需要一个已建立的 Connection；为空表示不需要
	ConnectionType string `protobuf:"bytes,7,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	// 建议超时；调用方可覆盖
	DefaultTimeout *durationpb.Duration `protobuf:"bytes,8,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"`
	// 是否幂等（AI / Workflow 重试策略参考）
	Idempotent bool `protobuf:"varint,9,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	// 标签，用于 Marketplace 检索与 UI 分类
	Tags          []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDefinition) Reset() {
	*x = CommandDefinition{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDefinition) ProtoMessage() {}

func (x *CommandDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDefinition.ProtoReflect.Descriptor instead.
func (*CommandDefinition) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CommandDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandDefinition) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

func (x *CommandDefinition) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *CommandDefinition) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *CommandDefinition) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *CommandDefinition) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *CommandDefinition) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *CommandDefinition) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *CommandDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RecipeDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Permission  Permission             `protobuf:"varint,3,opt,name=permission,proto3,enum=mow.plugin.v1.Permission" json:"permission,omitempty"`
	// Recipe 内部由若干 Command 组成，定义细节由 Core 侧的 YAML 解析生成
	// 此处仅暴露元信息供注册与展示
	CommandIds    []string `protobuf:"bytes,4,rep,name=command_ids,json=commandIds,proto3" json:"command_ids,omitempty"`
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeDefinition) Reset() {
	*x = RecipeDefinition{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeDefinition) ProtoMessage() {}

func (x *RecipeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeDefinition.ProtoReflect.Descriptor instead.
func (*RecipeDefinition) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *RecipeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeDefinition) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

func (x *RecipeDefinition) GetCommandIds() []string {
	if x != nil {
		return x.CommandIds
	}
	return nil
}

func (x *RecipeDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Permission    Permission             `protobuf:"varint,3,opt,name=permission,proto3,enum=mow.plugin.v1.Permission" json:"permission,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowDefinition) GetPermission() Permission {
	if x != nil {
		return x.Permission
	}
	return Permission_PERMISSION_UNSPECIFIED
}

func (x *WorkflowDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户为该 Plugin 提供的配置（来自 config 文件的对应 section）
	Settings *structpb.Struct `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// Core 版本，插件可据此启用兼容分支
	CoreVersion string `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	// 数据目录（插件可持久化数据）
	DataDir       string `protobuf:"bytes,3,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *InitRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *InitRequest) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *InitRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 若初始化失败，填充 error
	Error         *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InitResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=mow.plugin.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局唯一执行标识（由 Core 生成，ULID / UUIDv7）
	AuditId string `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	// Plugin 内部 Command ID
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Command 参数（对应 CommandDefinition.input_schema）
	Params *structpb.Struct `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// 可选：已建立的连接 ID，由 Core 分配
	// Plugin 通过 ConnectionHandle 服务反查（未来扩展），
	// v0.1 由 Core 侧组合，直接把连接凭据以只读方式传给 Plugin
	ConnectionId string `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// 调用者身份（用于审计）
	Caller *Caller `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	// 覆盖默认超时（0 表示使用 CommandDefinition.default_timeout）
	Timeout *durationpb.Duration `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// 若 Command 权限为 DANGEROUS，此字段必须为 true
	// Core 会在调用前完成二次确认
	Confirmed     bool `protobuf:"varint,7,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *ExecuteRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ExecuteRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ExecuteRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ExecuteRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 执行是否成功；等价于 error == nil
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 结构化输出（对应 CommandDefinition.output_schema）
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 错误信息（若失败）
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Plugin 侧耗时
	Duration *durationpb.Duration `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	// Plugin 附加的可观测字段（打点、Trace ID 等）
	Attributes    map[string]string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecuteResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecuteResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ExecuteResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ExecuteStreamMessage 是 Execute 流式协议的载体。
// - 首条消息由 Client 发送 StartExecute，声明本次调用
// - 后续 Client 侧可发送 Stdin / Signal / Close
// - Server 侧持续发送 Chunk（stdout/stderr/结构化增量），并以 Final 结束
type ExecuteStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteStreamMessage_Start
	//	*ExecuteStreamMessage_Stdin
	//	*ExecuteStreamMessage_Signal
	//	*ExecuteStreamMessage_Close
	//	*ExecuteStreamMessage_Chunk
	//	*ExecuteStreamMessage_Final
	Payload       isExecuteStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamMessage) Reset() {
	*x = ExecuteStreamMessage{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamMessage) ProtoMessage() {}

func (x *ExecuteStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamMessage.ProtoReflect.Descriptor instead.
func (*ExecuteStreamMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteStreamMessage) GetPayload() isExecuteStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteStreamMessage) GetStart() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecuteStreamMessage) GetStdin() *Stdin {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecuteStreamMessage) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ExecuteStreamMessage) GetClose() *Close {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ExecuteStreamMessage) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ExecuteStreamMessage) GetFinal() *Final {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteStreamMessage_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isExecuteStreamMessage_Payload interface {
	isExecuteStreamMessage_Payload()
}

type ExecuteStreamMessage_Start struct {
	// Client → Server：启动执行
	Start *ExecuteRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecuteStreamMessage_Stdin struct {
	// Client → Server：向 Command 提供标准输入（例如 SSH 交互）
	Stdin *Stdin `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecuteStreamMessage_Signal struct {
	// Client → Server：发送信号（如取消 / SIGINT / SIGTERM）
	Signal *Signal `protobuf:"bytes,3,opt,name=signal,proto3,oneof"`
}

type ExecuteStreamMessage_Close struct {
	// Client → Server：关闭输入端
	Close *Close `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type ExecuteStreamMessage_Chunk struct {
	// Server → Client：一段增量输出
	Chunk *Chunk `protobuf:"bytes,5,opt,name=chunk,proto3,oneof"`
}

type ExecuteStreamMessage_Final struct {
	// Server → Client：结束帧
	Final *Final `protobuf:"bytes,6,opt,name=final,proto3,oneof"`
}

func (*ExecuteStreamMessage_Start) isExecuteStreamMessage_Payload() {}

func (*ExecuteStreamMessage_Stdin) isExecuteStreamMessage_Payload() {}

func (*ExecuteStreamMessage_Signal) isExecuteStreamMessage_Payload() {}

func (*ExecuteStreamMessage_Close) isExecuteStreamMessage_Payload() {}

func (*ExecuteStreamMessage_Chunk) isExecuteStreamMessage_Payload() {}

func (*ExecuteStreamMessage_Final) isExecuteStreamMessage_Payload() {}

type Stdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stdin) Reset() {
	*x = Stdin{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdin) ProtoMessage() {}

func (x *Stdin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdin.ProtoReflect.Descriptor instead.
func (*Stdin) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Stdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  SignalType             `protobuf:"varint,1,opt,name=type,proto3,enum=mow.plugin.v1.SignalType" json:"type,omitempty"`
	// 可选负载（例：WINCH 时的 rows/cols）
	Payload       *structpb.Struct `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *Signal) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *Signal) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

type Chunk struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stream ChunkStream            `protobuf:"varint,1,opt,name=stream,proto3,enum=mow.plugin.v1.ChunkStream" json:"stream,omitempty"`
	// 原始字节（stdout/stderr）
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 结构化事件（仅当 stream = STRUCTURED 时）
	Event *structpb.Struct `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	// 序号，用于客户端排序 / 断点续传（可选）
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Chunk) GetStream() ChunkStream {
	if x != nil {
		return x.Stream
	}
	return ChunkStream_CHUNK_STREAM_UNSPECIFIED
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetEvent() *structpb.Struct {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Chunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Chunk) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type Final struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 最终结构化结果（可选，例如统计信息）
	Data  *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error *Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// 进程退出码（若 Command 是外部进程包装）
	ExitCode      int32                `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Duration      *durationpb.Duration `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Final) Reset() {
	*x = Final{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Final) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Final) ProtoMessage() {}

func (x *Final) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Final.ProtoReflect.Descriptor instead.
func (*Final) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Final) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Final) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Final) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Final) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Final) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// 调用来源，用于审计与权限判定
type Caller struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 触发来源
	Type CallerType `protobuf:"varint,1,opt,name=type,proto3,enum=mow.plugin.v1.CallerType" json:"type,omitempty"`
	// 用户标识（本地用户名 / RBAC 主体）
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// 可选：AI 会话 ID（当 type = AI）
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 可选：上游 auditId（追溯长链路调用）
	ParentAuditId string `protobuf:"bytes,4,opt,name=parent_audit_id,json=parentAuditId,proto3" json:"parent_audit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caller) Reset() {
	*x = Caller{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *Caller) GetType() CallerType {
	if x != nil {
		return x.Type
	}
	return CallerType_CALLER_TYPE_UNSPECIFIED
}

func (x *Caller) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Caller) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Caller) GetParentAuditId() string {
	if x != nil {
		return x.ParentAuditId
	}
	return ""
}

// 统一错误结构（对应 CommandResult.error）
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 稳定错误码，例："SSH_AUTH_FAILED"、"PARAM_INVALID"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 用户可读消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 结构化详情（栈、字段、Provider 原始错误）
	Details *structpb.Struct `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// 是否可重试（供 Workflow 决策）
	Retryable     bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\rmow.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x11\n" +
	"\x0fMetadataRequest\"\xb2\x02\n" +
	"\x10MetadataResponse\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.mow.plugin.v1.PluginMetadataR\bmetadata\x12<\n" +
	"\bcommands\x18\x02 \x03(\v2 .mow.plugin.v1.CommandDefinitionR\bcommands\x129\n" +
	"\arecipes\x18\x03 \x03(\v2\x1f.mow.plugin.v1.RecipeDefinitionR\arecipes\x12?\n" +
	"\tworkflows\x18\x04 \x03(\v2!.mow.plugin.v1.WorkflowDefinitionR\tworkflows\x12)\n" +
	"\x10connection_types\x18\x05 \x03(\tR\x0fconnectionTypes\"\x92\x02\n" +
	"\x0ePluginMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bhomepage\x18\x06 \x01(\tR\bhomepage\x12\x18\n" +
	"\alicense\x18\a \x01(\tR\alicense\x12!\n" +
	"\fcore_version\x18\b \x01(\tR\vcoreVersion\x12/\n" +
	"\x13plugin_dependencies\x18\t \x03(\tR\x12pluginDependencies\"\x87\x03\n" +
	"\x11CommandDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2\x19.mow.plugin.v1.PermissionR\n" +
	"permission\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12!\n" +
	"\finput_schema\x18\x05 \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x06 \x01(\tR\foutputSchema\x12'\n" +
	"\x0fconnection_type\x18\a \x01(\tR\x0econnectionType\x12B\n" +
	"\x0fdefault_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0edefaultTimeout\x12\x1e\n" +
	"\n" +
	"idempotent\x18\t \x01(\bR\n" +
	"idempotent\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"\xb4\x01\n" +
	"\x10RecipeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2\x19.mow.plugin.v1.PermissionR\n" +
	"permission\x12\x1f\n" +
	"\vcommand_ids\x18\x04 \x03(\tR\n" +
	"commandIds\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x95\x01\n" +
	"\x12WorkflowDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2\x19.mow.plugin.v1.PermissionR\n" +
	"permission\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x80\x01\n" +
	"\vInitRequest\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x19\n" +
	"\bdata_dir\x18\x03 \x01(\tR\adataDir\":\n" +
	"\fInitResponse\x12*\n" +
	"\x05error\x18\x01 \x01(\v2\x14.mow.plugin.v1.ErrorR\x05error\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x14\n" +
	"\x12HealthCheckRequest\"d\n" +
	"\x13HealthCheckResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.mow.plugin.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa2\x02\n" +
	"\x0eExecuteRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x12-\n" +
	"\x06caller\x18\x05 \x01(\v2\x15.mow.plugin.v1.CallerR\x06caller\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1c\n" +
	"\tconfirmed\x18\a \x01(\bR\tconfirmed\"\xc0\x02\n" +
	"\x0fExecuteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x14.mow.plugin.v1.ErrorR\x05error\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12N\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2..mow.plugin.v1.ExecuteResponse.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\x14ExecuteStreamMessage\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1d.mow.plugin.v1.ExecuteRequestH\x00R\x05start\x12,\n" +
	"\x05stdin\x18\x02 \x01(\v2\x14.mow.plugin.v1.StdinH\x00R\x05stdin\x12/\n" +
	"\x06signal\x18\x03 \x01(\v2\x15.mow.plugin.v1.SignalH\x00R\x06signal\x12,\n" +
	"\x05close\x18\x04 \x01(\v2\x14.mow.plugin.v1.CloseH\x00R\x05close\x12,\n" +
	"\x05chunk\x18\x05 \x01(\v2\x14.mow.plugin.v1.ChunkH\x00R\x05chunk\x12,\n" +
	"\x05final\x18\x06 \x01(\v2\x14.mow.plugin.v1.FinalH\x00R\x05finalB\t\n" +
	"\apayload\"\x1b\n" +
	"\x05Stdin\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"j\n" +
	"\x06Signal\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.mow.plugin.v1.SignalTypeR\x04type\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"\a\n" +
	"\x05Close\"\xbc\x01\n" +
	"\x05Chunk\x122\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1a.mow.plugin.v1.ChunkStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12-\n" +
	"\x05event\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05event\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12*\n" +
	"\x02ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\xc4\x01\n" +
	"\x05Final\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x14.mow.plugin.v1.ErrorR\x05error\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\x92\x01\n" +
	"\x06Caller\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.mow.plugin.v1.CallerTypeR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12&\n" +
	"\x0fparent_audit_id\x18\x04 \x01(\tR\rparentAuditId\"\x86\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable*\x85\x01\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPERMISSION_READ\x10\x01\x12\x14\n" +
	"\x10PERMISSION_WRITE\x10\x02\x12\x16\n" +
	"\x12PERMISSION_EXECUTE\x10\x03\x12\x18\n" +
	"\x14PERMISSION_DANGEROUS\x10\x04*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03*\x99\x01\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SIGNAL_TYPE_CANCEL\x10\x01\x12\x13\n" +
	"\x0fSIGNAL_TYPE_INT\x10\x02\x12\x14\n" +
	"\x10SIGNAL_TYPE_TERM\x10\x03\x12\x14\n" +
	"\x10SIGNAL_TYPE_KILL\x10\x04\x12\x15\n" +
	"\x11SIGNAL_TYPE_WINCH\x10\x05*z\n" +
	"\vChunkStream\x12\x1c\n" +
	"\x18CHUNK_STREAM_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHUNK_STREAM_STDOUT\x10\x01\x12\x17\n" +
	"\x13CHUNK_STREAM_STDERR\x10\x02\x12\x1b\n" +
	"\x17CHUNK_STREAM_STRUCTURED\x10\x03*\xb2\x01\n" +
	"\n" +
	"CallerType\x12\x1b\n" +
	"\x17CALLER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCALLER_TYPE_CLI\x10\x01\x12\x17\n" +
	"\x13CALLER_TYPE_DESKTOP\x10\x02\x12\x13\n" +
	"\x0fCALLER_TYPE_API\x10\x03\x12\x12\n" +
	"\x0eCALLER_TYPE_AI\x10\x04\x12\x18\n" +
	"\x14CALLER_TYPE_WORKFLOW\x10\x05\x12\x16\n" +
	"\x12CALLER_TYPE_RECIPE\x10\x062\xe2\x03\n" +
	"\x06Plugin\x12K\n" +
	"\bMetadata\x12\x1e.mow.plugin.v1.MetadataRequest\x1a\x1f.mow.plugin.v1.MetadataResponse\x12?\n" +
	"\x04Init\x12\x1a.mow.plugin.v1.InitRequest\x1a\x1b.mow.plugin.v1.InitResponse\x12K\n" +
	"\bShutdown\x12\x1e.mow.plugin.v1.ShutdownRequest\x1a\x1f.mow.plugin.v1.ShutdownResponse\x12T\n" +
	"\vHealthCheck\x12!.mow.plugin.v1.HealthCheckRequest\x1a\".mow.plugin.v1.HealthCheckResponse\x12H\n" +
	"\aExecute\x12\x1d.mow.plugin.v1.ExecuteRequest\x1a\x1e.mow.plugin.v1.ExecuteResponse\x12]\n" +
	"\rExecuteStream\x12#.mow.plugin.v1.ExecuteStreamMessage\x1a#.mow.plugin.v1.ExecuteStreamMessage(\x010\x01B'Z%github.com/mow/mow/sdk/proto;pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_plugin_proto_goTypes = []any{
	(Permission)(0),               // 0: mow.plugin.v1.Permission
	(HealthStatus)(0),             // 1: mow.plugin.v1.HealthStatus
	(SignalType)(0),               // 2: mow.plugin.v1.SignalType
	(ChunkStream)(0),              // 3: mow.plugin.v1.ChunkStream
	(CallerType)(0),               // 4: mow.plugin.v1.CallerType
	(*MetadataRequest)(nil),       // 5: mow.plugin.v1.MetadataRequest
	(*MetadataResponse)(nil),      // 6: mow.plugin.v1.MetadataResponse
	(*PluginMetadata)(nil),        // 7: mow.plugin.v1.PluginMetadata
	(*CommandDefinition)(nil),     // 8: mow.plugin.v1.CommandDefinition
	(*RecipeDefinition)(nil),      // 9: mow.plugin.v1.RecipeDefinition
	(*WorkflowDefinition)(nil),    // 10: mow.plugin.v1.WorkflowDefinition
	(*InitRequest)(nil),           // 11: mow.plugin.v1.InitRequest
	(*InitResponse)(nil),          // 12: mow.plugin.v1.InitResponse
	(*ShutdownRequest)(nil),       // 13: mow.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 14: mow.plugin.v1.ShutdownResponse
	(*HealthCheckRequest)(nil),    // 15: mow.plugin.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 16: mow.plugin.v1.HealthCheckResponse
	(*ExecuteRequest)(nil),        // 17: mow.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 18: mow.plugin.v1.ExecuteResponse
	(*ExecuteStreamMessage)(nil),  // 19: mow.plugin.v1.ExecuteStreamMessage
	(*Stdin)(nil),                 // 20: mow.plugin.v1.Stdin
	(*Signal)(nil),                // 21: mow.plugin.v1.Signal
	(*Close)(nil),                 // 22: mow.plugin.v1.Close
	(*Chunk)(nil),                 // 23: mow.plugin.v1.Chunk
	(*Final)(nil),                 // 24: mow.plugin.v1.Final
	(*Caller)(nil),                // 25: mow.plugin.v1.Caller
	(*Error)(nil),                 // 26: mow.plugin.v1.Error
	nil,                           // 27: mow.plugin.v1.ExecuteResponse.AttributesEntry
	(*durationpb.Duration)(nil),   // 28: google.protobuf.Duration
	(*structpb.Struct)(nil),       // 29: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	7,  // 0: mow.plugin.v1.MetadataResponse.metadata:type_name -> mow.plugin.v1.PluginMetadata
	8,  // 1: mow.plugin.v1.MetadataResponse.commands:type_name -> mow.plugin.v1.CommandDefinition
	9,  // 2: mow.plugin.v1.MetadataResponse.recipes:type_name -> mow.plugin.v1.RecipeDefinition
	10, // 3: mow.plugin.v1.MetadataResponse.workflows:type_name -> mow.plugin.v1.WorkflowDefinition
	0,  // 4: mow.plugin.v1.CommandDefinition.permission:type_name -> mow.plugin.v1.Permission
	28, // 5: mow.plugin.v1.CommandDefinition.default_timeout:type_name -> google.protobuf.Duration
	0,  // 6: mow.plugin.v1.RecipeDefinition.permission:type_name -> mow.plugin.v1.Permission
	0,  // 7: mow.plugin.v1.WorkflowDefinition.permission:type_name -> mow.plugin.v1.Permission
	29, // 8: mow.plugin.v1.InitRequest.settings:type_name -> google.protobuf.Struct
	26, // 9: mow.plugin.v1.InitResponse.error:type_name -> mow.plugin.v1.Error
	1,  // 10: mow.plugin.v1.HealthCheckResponse.status:type_name -> mow.plugin.v1.HealthStatus
	29, // 11: mow.plugin.v1.ExecuteRequest.params:type_name -> google.protobuf.Struct
	25, // 12: mow.plugin.v1.ExecuteRequest.caller:type_name -> mow.plugin.v1.Caller
	28, // 13: mow.plugin.v1.ExecuteRequest.timeout:type_name -> google.protobuf.Duration
	29, // 14: mow.plugin.v1.ExecuteResponse.data:type_name -> google.protobuf.Struct
	26, // 15: mow.plugin.v1.ExecuteResponse.error:type_name -> mow.plugin.v1.Error
	28, // 16: mow.plugin.v1.ExecuteResponse.duration:type_name -> google.protobuf.Duration
	27, // 17: mow.plugin.v1.ExecuteResponse.attributes:type_name -> mow.plugin.v1.ExecuteResponse.AttributesEntry
	17, // 18: mow.plugin.v1.ExecuteStreamMessage.start:type_name -> mow.plugin.v1.ExecuteRequest
	20, // 19: mow.plugin.v1.ExecuteStreamMessage.stdin:type_name -> mow.plugin.v1.Stdin
	21, // 20: mow.plugin.v1.ExecuteStreamMessage.signal:type_name -> mow.plugin.v1.Signal
	22, // 21: mow.plugin.v1.ExecuteStreamMessage.close:type_name -> mow.plugin.v1.Close
	23, // 22: mow.plugin.v1.ExecuteStreamMessage.chunk:type_name -> mow.plugin.v1.Chunk
	24, // 23: mow.plugin.v1.ExecuteStreamMessage.final:type_name -> mow.plugin.v1.Final
	2,  // 24: mow.plugin.v1.Signal.type:type_name -> mow.plugin.v1.SignalType
	29, // 25: mow.plugin.v1.Signal.payload:type_name -> google.protobuf.Struct
	3,  // 26: mow.plugin.v1.Chunk.stream:type_name -> mow.plugin.v1.ChunkStream
	29, // 27: mow.plugin.v1.Chunk.event:type_name -> google.protobuf.Struct
	30, // 28: mow.plugin.v1.Chunk.ts:type_name -> google.protobuf.Timestamp
	29, // 29: mow.plugin.v1.Final.data:type_name -> google.protobuf.Struct
	26, // 30: mow.plugin.v1.Final.error:type_name -> mow.plugin.v1.Error
	28, // 31: mow.plugin.v1.Final.duration:type_name -> google.protobuf.Duration
	4,  // 32: mow.plugin.v1.Caller.type:type_name -> mow.plugin.v1.CallerType
	29, // 33: mow.plugin.v1.Error.details:type_name -> google.protobuf.Struct
	5,  // 34: mow.plugin.v1.Plugin.Metadata:input_type -> mow.plugin.v1.MetadataRequest
	11, // 35: mow.plugin.v1.Plugin.Init:input_type -> mow.plugin.v1.InitRequest
	13, // 36: mow.plugin.v1.Plugin.Shutdown:input_type -> mow.plugin.v1.ShutdownRequest
	15, // 37: mow.plugin.v1.Plugin.HealthCheck:input_type -> mow.plugin.v1.HealthCheckRequest
	17, // 38: mow.plugin.v1.Plugin.Execute:input_type -> mow.plugin.v1.ExecuteRequest
	19, // 39: mow.plugin.v1.Plugin.ExecuteStream:input_type -> mow.plugin.v1.ExecuteStreamMessage
	6,  // 40: mow.plugin.v1.Plugin.Metadata:output_type -> mow.plugin.v1.MetadataResponse
	12, // 41: mow.plugin.v1.Plugin.Init:output_type -> mow.plugin.v1.InitResponse
	14, // 42: mow.plugin.v1.Plugin.Shutdown:output_type -> mow.plugin.v1.ShutdownResponse
	16, // 43: mow.plugin.v1.Plugin.HealthCheck:output_type -> mow.plugin.v1.HealthCheckResponse
	18, // 44: mow.plugin.v1.Plugin.Execute:output_type -> mow.plugin.v1.ExecuteResponse
	19, // 45: mow.plugin.v1.Plugin.ExecuteStream:output_type -> mow.plugin.v1.ExecuteStreamMessage
	40, // [40:46] is the sub-list for method output_type
	34, // [34:40] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[14].OneofWrappers = []any{
		(*ExecuteStreamMessage_Start)(nil),
		(*ExecuteStreamMessage_Stdin)(nil),
		(*ExecuteStreamMessage_Signal)(nil),
		(*ExecuteStreamMessage_Close)(nil),
		(*ExecuteStreamMessage_Chunk)(nil),
		(*ExecuteStreamMessage_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
